#### Floor
* The tool floor returns the floor of the input element-wise.
The floor of x is the largest integer i where i <= x 

#### Ceil
* The tool ceil returns the ceiling of the input element-wise.
The ceiling of x is the smallest integer i where i >= x 

#### Rint
* The rint tool rounds to the nearest integer of input element-wise.

In [5]:
## Example
import numpy 

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print (numpy.ceil(my_array))
print(numpy.floor(my_array))
print(numpy.rint(my_array))

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


* You are given a 2-D array with dimensions X.
* Your task is to perform the sum tool over axis 0 and then find the product of that result.

Input Format
* The first line of input contains space separated values of N and M.
The next N lines contains M space separated integers.

Output Format
* Compute the sum along axis . Then, print the product of that sum.

In [10]:
import numpy as np 
N, M= map(int, input().split()) #2-D array

array = []

for _ in range(N):
  row = list(map(int, input().split()))
  array.append(row)

array = np.array(array)
sum_result = np.sum(array, axis=0)
prod_result = np.prod(sum_result)

print(prod_result)

24
